name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PASO CLAVE: Instala Flutter en el servidor de GitHub
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # PASO 2: Descarga las librerías de tu proyecto (firebase_core, etc.)
      - run: flutter pub get

      # PASO 3: Compila la versión Web
      - run: flutter build web

      # PASO 4: Sube el resultado a Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELOS_RUBRIK }}'
          channelId: live
          projectId: elos-rubrik
